# use container-based infrastructure
sudo: false

language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - boost-latest
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8
      - libboost1.55-all-dev
      - libssl-dev
      - openssl

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" && $CXX --version; fi
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make VERBOSE=1
