# use container-based infrastructure
sudo: false

language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - g++-4.8
      - libboost1.55-all-dev
      - libssl-dev
      - openssl

script:
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make VERBOSE=1
